### ISSUE TITLE
Something went wrong : [object Object]

### ISSUE THREAD

**Issue by TaghikhaniAlireza** [k1nd0ne/VolWeb#7] opened 2023-08-17 08:16 UTC
Hi 
I'm trying to create a new investigation with (user and also admin account) but after clicking on create at the bottom, in the upload process, I frequently face this error: Something went wrong : [object Object], I watched tutorials but I don't what happened in that upload process. 
I run docker on the Ubuntu 20.04 release. 
@k1nd0ne

**Comment by k1nd0ne** [comment] 2023-08-17 13:37
Hello, 
Thank you for the submission of the issue. 

I will investigate on this.

Can you please provide the following information : 
 - The docker logs after the error.
 - The size of the memory image you are uploading.

Best regards.

**Comment by TaghikhaniAlireza** [comment] 2023-08-17 15:32
Thanks for respond
Here is more information:

- The size of the memory image you are uploading : 525 MB

- docker log:

`
==> /var/lib/docker/containers/b9612bbd98debfac3295e864fd28d7d25ecd7ffc2893df7cd0807539a6f0d524/b9612bbd98debfac3295e864fd28d7d25ecd7ffc2893df7cd0807539a6f0d524-json.log <==
{"log":"[2023-08-17 15:14:44 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)\n","stream":"stderr","time":"2023-08-17T15:14:44.753886288Z"}
{"log":"[2023-08-17 15:14:44 +0000] [1] [INFO] Using worker: sync\n","stream":"stderr","time":"2023-08-17T15:14:44.753891485Z"}
{"log":"[2023-08-17 15:14:44 +0000] [17] [INFO] Booting worker with pid: 17\n","stream":"stderr","time":"2023-08-17T15:14:44.882358295Z"}
{"log":"[2023-08-17 15:14:44 +0000] [18] [INFO] Booting worker with pid: 18\n","stream":"stderr","time":"2023-08-17T15:14:44.902374078Z"}
{"log":"[2023-08-17 15:14:44 +0000] [19] [INFO] Booting worker with pid: 19\n","stream":"stderr","time":"2023-08-17T15:14:44.982322698Z"}
{"log":"[2023-08-17 15:14:45 +0000] [20] [INFO] Booting worker with pid: 20\n","stream":"stderr","time":"2023-08-17T15:14:45.10574433Z"}
{"log":"Internal Server Error: /investigations/new_invest/\n","stream":"stderr","time":"2023-08-17T15:22:36.168149945Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2023-08-17T15:22:36.168186018Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n","stream":"stderr","time":"2023-08-17T15:22:36.168192276Z"}
{"log":"    response = get_response(request)\n","stream":"stderr","time":"2023-08-17T15:22:36.168197119Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py\", line 181, in _get_response\n","stream":"stderr","time":"2023-08-17T15:22:36.168201618Z"}
{"log":"    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n","stream":"stderr","time":"2023-08-17T15:22:36.168215166Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py\", line 21, in _wrapped_view\n","stream":"stderr","time":"2023-08-17T15:22:36.168219586Z"}
{"log":"    return view_func(request, *args, **kwargs)\n","stream":"stderr","time":"2023-08-17T15:22:36.168224545Z"}
{"log":"  File \"/home/app/web/investigations/views.py\", line 87, in new_invest\n","stream":"stderr","time":"2023-08-17T15:22:36.168229431Z"}
{"log":"    with open(path, 'wb+') as destination:\n","stream":"stderr","time":"2023-08-17T15:22:36.168234387Z"}
{"log":"PermissionError: [Errno 13] Permission denied: 'Cases/052ebfaa-3919-4d52-ad72-362f845f1fa9_stuxnet.vmem'\n","stream":"stderr","time":"2023-08-17T15:22:36.1682389Z"}
{"log":"ERROR:django.request:Internal Server Error: /investigations/new_invest/\n","stream":"stderr","time":"2023-08-17T15:22:36.168243552Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2023-08-17T15:22:36.16825799Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n","stream":"stderr","time":"2023-08-17T15:22:36.168262855Z"}
{"log":"    response = get_response(request)\n","stream":"stderr","time":"2023-08-17T15:22:36.168267745Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py\", line 181, in _get_response\n","stream":"stderr","time":"2023-08-17T15:22:36.168272436Z"}
{"log":"    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n","stream":"stderr","time":"2023-08-17T15:22:36.168277165Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py\", line 21, in _wrapped_view\n","stream":"stderr","time":"2023-08-17T15:22:36.168297233Z"}
{"log":"    return view_func(request, *args, **kwargs)\n","stream":"stderr","time":"2023-08-17T15:22:36.168304497Z"}
{"log":"  File \"/home/app/web/investigations/views.py\", line 87, in new_invest\n","stream":"stderr","time":"2023-08-17T15:22:36.168309016Z"}
{"log":"    with open(path, 'wb+') as destination:\n","stream":"stderr","time":"2023-08-17T15:22:36.168313601Z"}
{"log":"PermissionError: [Errno 13] Permission denied: 'Cases/052ebfaa-3919-4d52-ad72-362f845f1fa9_stuxnet.vmem'\n","stream":"stderr","time":"2023-08-17T15:22:36.168318099Z"}
{"log":"Internal Server Error: /investigations/new_invest/\n","stream":"stderr","time":"2023-08-17T15:25:53.019024922Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2023-08-17T15:25:53.019077069Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n","stream":"stderr","time":"2023-08-17T15:25:53.019087054Z"}
{"log":"    response = get_response(request)\n","stream":"stderr","time":"2023-08-17T15:25:53.019109373Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py\", line 181, in _get_response\n","stream":"stderr","time":"2023-08-17T15:25:53.019115111Z"}
{"log":"    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n","stream":"stderr","time":"2023-08-17T15:25:53.019120588Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py\", line 21, in _wrapped_view\n","stream":"stderr","time":"2023-08-17T15:25:53.019125902Z"}
{"log":"    return view_func(request, *args, **kwargs)\n","stream":"stderr","time":"2023-08-17T15:25:53.019131325Z"}
{"log":"  File \"/home/app/web/investigations/views.py\", line 87, in new_invest\n","stream":"stderr","time":"2023-08-17T15:25:53.019136579Z"}
{"log":"    with open(path, 'wb+') as destination:\n","stream":"stderr","time":"2023-08-17T15:25:53.019141995Z"}
{"log":"PermissionError: [Errno 13] Permission denied: 'Cases/1fac0cda-cba0-47fb-824b-8ac15fae8650_stuxnet.vmem'\n","stream":"stderr","time":"2023-08-17T15:25:53.019147262Z"}
{"log":"ERROR:django.request:Internal Server Error: /investigations/new_invest/\n","stream":"stderr","time":"2023-08-17T15:25:53.019152641Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2023-08-17T15:25:53.01915792Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n","stream":"stderr","time":"2023-08-17T15:25:53.01916326Z"}
{"log":"    response = get_response(request)\n","stream":"stderr","time":"2023-08-17T15:25:53.019168672Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py\", line 181, in _get_response\n","stream":"stderr","time":"2023-08-17T15:25:53.019173888Z"}
{"log":"    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n","stream":"stderr","time":"2023-08-17T15:25:53.019179291Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py\", line 21, in _wrapped_view\n","stream":"stderr","time":"2023-08-17T15:25:53.0191846Z"}
{"log":"    return view_func(request, *args, **kwargs)\n","stream":"stderr","time":"2023-08-17T15:25:53.019190088Z"}
{"log":"  File \"/home/app/web/investigations/views.py\", line 87, in new_invest\n","stream":"stderr","time":"2023-08-17T15:25:53.019195327Z"}
{"log":"    with open(path, 'wb+') as destination:\n","stream":"stderr","time":"2023-08-17T15:25:53.019200655Z"}
{"log":"PermissionError: [Errno 13] Permission denied: 'Cases/1fac0cda-cba0-47fb-824b-8ac15fae8650_stuxnet.vmem'\n","stream":"stderr","time":"2023-08-17T15:25:53.019205913Z"}
`

**Comment by k1nd0ne** [comment] 2023-08-19 12:25
Hello, 
Seems to be a problem with the mounted volume permissions on Linux.
I will try to figure this out.

Dirty quick fix you can do is: 
```
cd Volweb/docker
docker-compose down 
chmod -R 777 cases
docker-compose up -d
```

Should work while I am working on a solution. 
Best regards.

**Comment by k1nd0ne** [comment] 2023-08-27 12:45
Hello the issue is now fixed by using named volumes.

Best regards.

**Closed by k1nd0ne** 2023-08-27 12:45 UTC
Labels: bug, review in progress
